### PR TITLE
Add Alt+backspace and Ctrl+u keybinds for deleting by word and by line, respectively

### LINKED ISSUE #227: Add Alt+Backspace to delete word leftwards
This is a standard in shell and would be nice to have it in atuin to delete a whole word quickly and clear the filter.

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes #227 

These are both standard shell key binds, so we should be able to use them at the Atuin prompt as well.

### CODE REVIEW

**Comment by ellie** [comment]
Before approving merging this, I'd like to consider using some sort of readline or other line editor. Or at least see if we can find one 

These are not standard shell bindings - they are eMacs bindings. Usually supported by the line editor your shell uses. They support vi input too :)

**Comment by mrjones2014** [comment]
There's this we could look at: https://github.com/kkawakam/rustyline

**Comment by mrjones2014** [comment]
Some alternatives found in the README of that project as well:

- https://github.com/murarth/linefeed
- https://github.com/redox-os/liner

**Comment by conradludgate** [comment]
Seems a bit ironic loading a history-aware line editor into a history search window and then not using it's history feature 😅

**Comment by ellie** [comment]
Yeah lol. I realised that they wouldn't work with our TUI stuff anyway, sooo 🤷‍♀️

**Review by ellie — APPROVED** [review]
Thanks for the work!! Would be cool to consider more eMacs and eventually vi bindings too

**Comment by conradludgate** [comment]
I like the idea of having more keybindings, Perhaps it's worth seeing if we can modularize some of these existing line editors to have a shared library for keybindings

**Comment by mrjones2014** [comment]
Yeah I'm not sure how we'd integrate rustyline with termion being an event-driven type thing. it seems like rustline wants to read the whole line at once.

**Comment by conradludgate** [comment]
Yeah all these readline alternatives take control of stdin/stdout so they don't work in our TUI environment. They're more for implementing a `sqlite` style prompt

**Pull request merged**
