### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OnePieceJoker**
Replace Sqlite with Postgresql

### CODE REVIEW

**Comment by ellie** [comment]
Why? This isn't true :) Only the sync server uses postgres

**Comment by OnePieceJoker** [comment]
I'm so sorry. I didn't read everything. Self-righteous modified README.md

**Comment by ellie** [comment]
haha, that's ok!

**Comment by OnePieceJoker** [comment]
Please allow me to write Chinese documentation for this project, 
I will create a new directory under the docs directory to store all the translation files.

**Comment by ellie** [comment]
Of course! That would be fantastic :)

**Pull request closed without merging**
