### PR TITLE
feat: nushell import

### PR DESCRIPTION
**Pull request by conradludgate**
- [x] import
- [ ] search
- [ ] history hook

### CODE REVIEW

**Comment by conradludgate** [comment]
Closing this for now since we are missing hook support from nushell to provide the key service that atuin provides. Can re-open in future but it would probably be better to start a fresh at that time

**Comment by maghsk** [comment]
Any progress on this issue?     XD
Nushell team has just released their 0.6.1!

**Comment by conradludgate** [comment]
As far as I can tell, nushell still doesn't support hooks that we need to provide custom history support https://github.com/nushell/nushell/issues/3872

**Comment by mcheshkov** [comment]
I am not an nushell expert, but it seems to me that `pre_execution` hook should be enough for basic integration
https://www.nushell.sh/book/hooks.html

**Pull request closed without merging**
