### PR TITLE
skim-demo

### PR DESCRIPTION
**Pull request by conradludgate**
If you are not satisfied with the current fuzzy search, please try this out and let us know if you find the results any better. This is ultimately a very subjective issue, but it's worth considering.

Install using
```sh
cargo install --locked --git https://github.com/ellie/atuin --branch skim-demo
```

### CODE REVIEW

**Comment by ellie** [comment]
I think it would make sense to get this merged as a new option in the next release. We can then get more people trying it out, and potentially replace the current fuzzy. Or at least make it the default!

**Comment by ellie** [comment]
I think it would be good to get this released asap under search_mode "skim"

We can then try to get a bunch of people trying it - if they like it, we can consider replacing the other fuzzy mode, or changing the default mode

**Comment by conradludgate** [comment]
Over-engineering, I can imagine restructuring the commands (**just for indexing, not as a source of truth**) to be

```
command_text{ id, text, count }
directories{ id, path }
host{ id, name }
executed { command_id, directory_id, session_id, host_id, timestamp }
```

To play with at some other time though. I cba now

**Review by ellie — APPROVED** [review]

**Comment by conradludgate** [comment]
Was asked to add cwd weighting but that can be added later, gonna merge as is for now so it's easier to play with

**Pull request merged**
