### PR TITLE
Run shellcheck on bash file

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref #64

### CODE REVIEW

**Comment by yuvipanda** [comment]
shellcheck doesn't support zsh unfortunately

**Comment by ellie** [comment]
> shellcheck doesn't support zsh unfortunately

that's a shame! 

Thank you for this one :rocket:

**Review by ellie — APPROVED** [review]

**Comment by ismith** [comment]
Shellcheck claims to, or at least https://github.com/ludeeus/action-shellcheck includes it in their list of suffixes - I'll take a pass at it.

**Comment by ismith** [comment]
... I stand corrected :sadpanda:

```
In src/shell/atuin.zsh line 1:
#!/bin/zsh
^-- SC1071: ShellCheck only supports sh/bash/dash/ksh scripts. Sorry!
```

(Shellcheck will run on the file if it lacks a shellbang, but ... I guess it's assuming it's bash? So I'm going to exclude it from files checked by the shellcheck action.)

**Pull request merged**
