### PR TITLE
README: add MacPorts installation instructions

### PR DESCRIPTION
**Pull request by herbygillot**
https://ports.macports.org/port/atuin/

### CODE REVIEW

**Review by ellie — APPROVED** [review]
Oh awesome! I didn't know there was a port too 😁 

Thank you so much for your contribution ❤️

**Comment by herbygillot** [comment]
No worries, thank _you_ for Atuin :)

**Comment by ellie** [comment]
I just realised you're the package maintainer there! That's awesome :) Please do let us know if you have any issues!

**Comment by herbygillot** [comment]
> I just realised you're the package maintainer there! That's awesome :) Please do let us know if you have any issues!

Of course. Thank you :)

**Pull request merged**
