### PR TITLE
Workspace reorder

### PR DESCRIPTION
**Pull request by utter-step**
* moved main crate (`atuin`) to be on the same level with other crates
* extracted common deps to workspace definition, so it would be easier to avoid having same multiple dependencies with slightly different versions (base64 was an example)
* slight fix to base64 usage, to comply with deprecation warning from v0.21

As a nice side-effect, `cargo test`/`cargo nextest run` now runs tests from all the crates in a workspace, compared to the main crate only, as before :)

What do you think?

### CODE REVIEW

**Comment by utter-step** [comment]
https://github.com/ellie/atuin/pull/868/commits/993e60f8dea81a1625a04285a617959ad09a0866 this commit updates deps and fixes chrono deprecations. It added a bunch of unwraps, but in each case – previously the code would also panic in the same conditions, it's just more obvious now :)

Aside from that – zero meaningful changes

**Comment by conradludgate** [comment]
You can revert the last commit as we'll be going with #806 soon

**Comment by utter-step** [comment]
> You can revert the last commit as we'll be going with https://github.com/ellie/atuin/pull/806 soon

Great! Reverted :)

**Review by ellie — APPROVED** [review]
This is great - thank you!

Seeing as this is your first time contributing, if you would like a holographic contributors-only Atuin sticker, then please fill out this [form!](https://notionforms.io/forms/contributors-stickers)

Either way - thank you so much for the time and effort here ✨

**Pull request merged**
