### PR TITLE
feat: add common default keybindings

### PR DESCRIPTION
**Pull request by stevenxxiu**
For [[Feature Request] Custom keyboard shortcuts · Issue #610 · ellie/atuin](https://github.com/ellie/atuin/issues/610).

### CODE REVIEW

**Comment by trygveaa** [comment]
I think it would be beneficial if this behaved in the same way as bash and zsh. The differences I see is that they always move to the beginning/end of the next word with ctrl-left/right. So with e.g. `test()-test` and the cursor at the end, ctrl-left first moves after `-` and then to the beginning. And then ctrl-right moves before `(` and then to the end. ctrl-delete and alt-backspace does the same movements, but deletes the words instead (ctrl-backspace doesn't do anything in me for bash or zsh, and just moves the cursor in this branch for me).

Another difference is that `_` is counted as a word separator in bash and zsh (I haven't checked all other symbols).

(I'm not affiliated with atuin btw, so these are just my personal opinions).

I also notice that if I press ctrl-right or ctrl-delete on an empty prompt, atuin panics with this branch.

**Comment by stevenxxiu** [comment]
> I also notice that if I press ctrl-right or ctrl-delete on an empty prompt, atuin panics with this branch.

Thanks for testing. Should be fixed now. I added a test case for that.

> I think it would be beneficial if this behaved in the same way as bash and zsh.

I made the word skipping action identical to *Sublime Text*, which is what I'm used to. In fact, I configured my *Zsh* line editor to behave the same way.

I tried your example of `test()-test`. The current behavior also matches my browser (*Vivaldi*).

I think word jumping behavior is up to personal preference. It makes sense to add some configuration option for this, but I'm not clear on what options would make most people happy. The only thing I could think of is to configure the value of `WORD_SEPARATORS`.

**Comment by trygveaa** [comment]
Ah, right, emacs-forward/backward-word and vi-forward/backward-word behave differently in zsh and none of them are the default. I think bash behaves the way I said by default though. I think it would make sense to stick close to the default behavior of common shells, since this is a tool for shell history. I'll defer to the maintainers here to decide this and to decide whether a configuration option should be added.

**Comment by conradludgate** [comment]
We already have a mechanism for deleting words: <kbd>Ctrl</kbd>-<kbd>W</kbd>. I've just tested it and it treats `test()-test` as a single word.

As I don't use this feature in any shell and I'm not an emacs/vim keybinding user I can't really comment on which behaviour works best here

**Comment by ellie** [comment]
> Ah, right, emacs-forward/backward-word and vi-forward/backward-word behave differently in zsh and none of them are the default. I think bash behaves the way I said by default though. I think it would make sense to stick close to the default behavior of common shells, since this is a tool for shell history. I'll defer to the maintainers here to decide this and to decide whether a configuration option should be added.

There doesn't really seem to be an obvious answer, so I think going for the default bash behaviour is the best option - I imagine most people will be used to this!

Otherwise, making things configurable would be 💯

**Comment by stevenxxiu** [comment]
I added `word_jump_mode` (`emacs`/`vi`) and `word_chars` options now.

Hope this matches your expectations of *Emacs* behavior. Please let me know if it's still incorrect in some way.

**Comment by stevenxxiu** [comment]
@ellie Sorry about the nag but have time to look at this?

**Review by ellie — APPROVED** [review]
I'm happy for this to go in, thank you for the work! 🚀 And apologies for the slower review :/

**Pull request merged**
