### PR TITLE
ignore JetBrains IDEs, tidy-up imports

### PR DESCRIPTION
**Pull request by panekj**
Imports sorted in order:
- stdlib
- external crates
- atuin/internal

### CODE REVIEW

**Comment by conradludgate** [comment]
I'm happy to accept this, could you create the relevant rustfmt.toml file to ensure it stays updated?

**Comment by panekj** [comment]
It requires `rustfmt` nightly, are you ok with that?

**Comment by conradludgate** [comment]
What features are you trying to use?

**Comment by panekj** [comment]
`imports_granularity` and `group_imports`

**Comment by panekj** [comment]
stable rustfmt only has `reorder_imports` which is... eh
https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=imports

**Comment by ellie** [comment]
I'd be happy to merge this with just `reorder_imports`, I don't really think it's worth depending on nightly fmt for this.

**Pull request merged**
