### PR TITLE
Add Alt+w to copy current command to clipboard

### LINKED ISSUE #130: Add shortcut to copy current selection to clipboard
Often I'm browsing my history to copy paste a command to someone else. Right now, I've to select it, hit enter, then copy paste it with my mouse. Instead, would be great to copy it directly with a keyboard shortcut

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes #130

### CODE REVIEW

**Comment by ellie** [comment]
I'd love to get this merged - once the build error is fixed I'm happy to approve!

**Comment by bl-ue** [comment]
Hey @yuvipanda — any progress?

**Comment by ellie** [comment]
Hey @yuvipanda! This one has been open for quite some time now, so I'm going to close it. Happy to reopen if anything changes!

**Comment by yuvipanda** [comment]
Sorry I haven't been able to follow up, @ellie! Closing it is the right thing to do for now

**Pull request closed without merging**
